class Configuration:

    AGREEMENT_TIMEOUT = 3
    WEAK_AGREEMENT_TIMEOUT = 6

    STABLE_CONNECTIONS = True
    SDO_NUMBER = 8  # 12
    MAX_NEIGHBORS_RATIO = 1/3
    NEIGHBOR_PROBABILITY = 62  # 55

    NODE_NUMBER = 4
    BUNDLE_PERCENTAGE = 55  # 70

    SAMPLE_FREQUENCY = .1

    SCHEDULING_TIME_LIMIT = 1

    LOG_LEVEL = "VERBOSE"

    RAP_INSTANCE = "config/rap_instance.json"
    RESULTS_FOLDER = "results"
